language: ruby
sudo: false
cache: bundler
script:
- bundle exec rake spec
rvm:
- 2.0.0
- 2.1.5
- 2.4.2
- 2.5
- 2.6
- 2.7
bundler_args: --without release
matrix:
  fast_finish: true
deploy:
  provider: rubygems
  on:
    rvm: 2.1.5
    tags: true
    all_branches: true
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
